--local UIPanelName = {}
--UIPanelName.PanelLayerType = CS.UILayerType.WindowsPlane
--
--function UIPanelName:Init()
--end
--
-----显示或者刷新界面
--function UIPanelName:Show()
--end
--
--function ondestroy()
--end
--
--return UIPanelName
