---@class UIAuctionPanel_AuctionItem_UnionAuction_Diamond:UIAuctionPanel_AuctionItem_AuctionBid 行会竞拍模板_钻石
local UIAuctionPanel_AuctionItem_UnionAuction_Diamond = {}

setmetatable(UIAuctionPanel_AuctionItem_UnionAuction_Diamond, luaComponentTemplates.UIAuctionPanel_AuctionItem_AuctionBid)



return UIAuctionPanel_AuctionItem_UnionAuction_Diamond